# Generated by Django 3.2.13 on 2022-05-28 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.IntegerField(default=0, unique=True)),
                ('level', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_num', models.IntegerField()),
                ('result_stt', models.TextField(null=True)),
                ('result_eye', models.TextField(null=True)),
                ('result_face', models.TextField(null=True)),
                ('result_add', models.TextField(null=True)),
                ('quest_id', models.ForeignKey(db_column='quest_id', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='interviewapp.question', to_field='quest_id')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
