# Generated by Django 3.2.13 on 2022-05-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
                ('name', models.TextField()),
                ('corp_name', models.ForeignKey(db_column='corp_name', on_delete=django.db.models.deletion.CASCADE, related_name='corp', to='homeapp.corporation', to_field='name')),
            ],
        ),
    ]
